url: "https://ItsYourAnirban.github.io/Black-Light-Ai"
baseurl: "/Black-Light-Ai"
title: "Black Light AI"
description: "Autonomous Cyber Threat & Risk Intelligence - Multi-Agent Cybersecurity Risk Assessment System"
author: "Team TRIPOD"
theme: jekyll-theme-minimal
